### ISSUE TITLE
Pillow 10.0.0 breaking change -- Image.ANTIALIAS deprecated

### ISSUE THREAD

**Issue by cestorer** [google-coral/pycoral#119]
### Description

Following coral setup documentation and ran into a breaking change introduced with Pillow 10.0.0. Image.ANTIALIAS has been deprecated and instead should just use Image.LANCZOS.

### Issue Type

Bug

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

```shell
home-mini@Mini MINGW64 /c/coral/pycoral (master)
$ python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
Traceback (most recent call last):
  File "C:\coral\pycoral\examples\classify_image.py", line 121, in <module>
    main()
  File "C:\coral\pycoral\examples\classify_image.py", line 79, in main
    image = Image.open(args.input).convert('RGB').resize(size, Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by feranick** [comment]
This has been fixed in the repo. Should be closed.
