### ISSUE TITLE
Issue when trying to run pycoral example in RPi 4

### ISSUE THREAD

**Issue by jpvalero** [google-coral/pycoral#145]
### Description

Hi! After installing the Edge TPU runtime in my RPi 4 and the pycoral library Im getting the following error when running the example: python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Linux

### Coral Device

USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.8

### Relevant Log Output

```shell
The output of the RPi is: 

python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 40, in <module>
    from pycoral.utils.edgetpu import make_interpreter
  File "/home/anavalero/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /home/anavalero/.pyenv/versions/3.8.19/lib/python3.8/site-packages/pycoral/pybind/_pywrap_coral.cpython-38-arm-linux-gnueabihf.so)
```
</details>

**Comment by zoldaten** [comment]
https://youtu.be/EA7_2qL3Iho
